import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: '웹 테스트',
  description: 'Generated by hyeonbinnn',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <Link href="/">홈</Link>
        </h1>
        <ol>
          <li>
            <Link href="/read/1">페이지</Link>
          </li>
          <li>
            <Link href="/read/2">페이지</Link>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">생성</Link>
          </li>
          <li>
            <Link href="/update/1">등록</Link>
          </li>
          <li>
            <input type="button" value="삭제" />
          </li>
        </ul>
      </body>
    </html>
  );
}
